### ISSUE TITLE
Separate DeltaScript into its own repository

### ISSUE THREAD

**Issue by jbunke** [jbunke/delta-time#13]
Separate only the grammars of DeltaScript into a dedicated language repository (jbunke/deltascript). That way, contents native to the `delta-time/script` module will merely represent a DeltaScript *implementation*.

This repository will host:

* Language specification
* Related documentation
* ANTLR to target language scaffolding
* Releases for JAR CLI distributions

### Tasks
* [x] create empty repo `deltascript` to house contents
* [x] populate with contents from `delta-time/script/antlr'
* [x] remove from 'delta-time' and 're-include' as submodule of 'deltascript' under directory name 'antlr'
