### ISSUE TITLE
Major refactor of Delta Time

### ISSUE THREAD

**Issue by jbunke** [jbunke/delta-time#7]
### Description
Delta Time should be streamlined into core behaviour, with extension functionality split off from the core module and packaged into separate JARs.

### Sub-Tasks
- [x] Investigate how IntelliJ builds JARs
- [x] Refactor IntelliJ project
  - [x] Refactor module structure
  - [x] Move .git and .gitignore to new root
- [x] Split contents into new modules
